### ISSUE TITLE
Assignment 8

### ISSUE THREAD

**Issue by quaiquai** [krs-world/bridges_assignments#25] opened 2018-06-02 17:40 UTC
Small PQ bug that duplicates 2 words

**Comment by esaule** [comment] 2018-06-02 21:17
I posted a C++ version. I will polish it and move to match the java version

**Comment by esaule** [comment] 2018-06-03 02:12
@squeetus 

I have a Java version of the heap in 8-PQBook. I am still working on it but there is something you could do maybe. The "Key" of the heap does not show on the visualization.

I could get it in the C++ version by overloading the getElementRepresentation of the MyHeapElement object (which derives from BinTreeElement). That is what the BSTElement does in C++ to show the Key.

But in the Java version of BSTElement, that function is commented out, which tells me that is not the way of doing this.

Could you look into that? The issue is certainly in the java client, I don't know how to pass that information to get it encoded in the JSON string.

**Comment by quaiquai** [comment] 2018-06-03 02:31
I noticed that as well when I built my heap. I will look into it and get back to you.

**Comment by esaule** [comment] 2018-06-03 02:34
I looked quickly at it. It seems in Java, everything is built from Element directly rather thand letting the different subclass do their own thing. Element::getElementRepresentation seems to be doing the heavy lifting for every possible datastructure. That is certainly the design problem. Not sure if we can safely fix that by the workshop.

**Comment by squeetus** [comment] 2018-06-03 17:07
After a bit of digging, I think the only way to easily do this would be to have MyHeapElement extend BSTElement rather than BinTreeElement. The former has a key attribute and overrides the _getRepresentation_ method (rather than letting Element do the work) to add the key to the JSON for that assignment. On the server side if the first tree node has a key attribute it automatically adds that label to the vis as well as the regular label.

**Comment by esaule** [comment] 2018-06-03 20:07
Thanks @squeetus for looking into it. So close to the workshop, that seems unwise to try to fix. Let's run the workshop like this and rediscuss how the json are crafted after the workshop is passed.

BTW, I saw your 1:59pm commit :)

Won't fix => closing.

**Closed by esaule** 2018-06-03 20:07 UTC
